### ISSUE TITLE
root user , 'dmidecode' warning

### ISSUE THREAD

**Issue by akumacxd** [fredrikaverpil/saltstack-docker#2] opened 2017-02-05 15:26 UTC
When starting the salt-master in the SUSE11SP4 environment, the following warning is printed:
2017-02-05 20:51:48,811 [salt.loaded.int.grains.core                            ][WARNING ][10593] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
2017-02-05 20:51:48,848 [salt.loaded.int.grains.core                            ][WARNING ][10607] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.

 # salt --version
salt 2016.3.4 (Boron)

**Comment by fredrikaverpil** [comment] 2017-02-05 16:11
Yes, this is a duplicate of the only other existing issue in this repository: #1

**Closed as completed by fredrikaverpil** 2017-02-05 16:11 UTC
Labels: duplicate

**Comment by fredrikaverpil** [comment] 2017-02-05 16:54
I've added a `yum install dmidecode` to my Dockerfile and made the container run `privileged` (in `docker-compose.yml`. Perhaps you can try to do something similar to your SUSE install?
